- name: Setup Desktop Environment
  hosts: desktop
  roles:
    - role: common
    - role: fonts
    - role: desktop
    - role: coding-tools
    - role: general-programs
    - role: coding-programs
    - role: gaming
  user: niclas
  vars:
    user: niclas
    desktop: gnome
    toolbox_version: "3.2.0.65851"
    nvm_version: "0.40.3"
  tasks:
