- name: Setup Server Environment
  hosts: server
  roles:
    - role: common-base
    - role: common-fonts
    - role: common-coding-base
    - role: server-security
  user: tiramisu
  vars:
    user: tiramisu
  tasks:
