- name: Testing roles and tasks
  hosts: test
  roles:
    - role: common-base
    - role: common-fonts
    - role: common-coding-base
    - role: common-coding-extra
    - role: desktop-environment
    - role: desktop-gaming
    - role: desktop-programs-coding
    - role: desktop-programs-general
  vars:
    user: "{{ ansible_user }}"
    desktop: gnome
    toolbox_version: "3.1.2.64642"
    nvm_version: "0.40.3"
  tasks:
