- name: Testing roles and tasks
  hosts: testvm
  roles:
    - role: common
    - role: fonts
    - role: desktop
    - role: coding-tools
    - role: general-programs
    - role: coding-programs
    - role: gaming
  user: niclas-vm
  vars:
    user: niclas-vm
    desktop: gnome
    toolbox_version: "3.1.2.64642"
    nvm_version: "0.40.3"
  tasks:
