---
# Docker
- name: Install docker
  ansible.builtin.script:
    cmd: docker.sh
  become: true

- name: Add docker to autostart
  ansible.builtin.systemd_service:
    enabled: true
    name: "docker"
  become: true

- name: Allow user to run docker commands
  ansible.builtin.user:
    name: "{{ user }}"
    append: true
    groups: 
      - docker
  become: true
