---
- name: Import fedora specific commons
  ansible.builtin.include_tasks: os_family/fedora.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Import git configs
  ansible.builtin.include_tasks: git.yml

# - nvim
# - ssh key
# - linux setup repo
# - shell-configuration
