---
- name: Import fedora specific commons
  ansible.builtin.include_tasks: os_family/fedora.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Import git configs
  ansible.builtin.include_tasks: git.yml

# Generate ssh key
- name: Generate SSH keypair
  community.crypto.openssh_keypair:
    path: /home/{{ user }}/.ssh/id_ed25519
    type: ed25519

- name: Check if shell is initialized
  ansible.builtin.stat:
    path: /home/{{ user }}/shell-configuration
  register: sc

- name: Create init script
  when: not (sc.stat.isdir is defined and sc.stat.isdir)
  ansible.builtin.copy:
    src: init-shell.sh
    dest: /home/{{ user }}/init-shell.sh
    mode: "755"
